DefaultContentLanguage = "en"
baseURL                = "https://playleft.com"
# copyright              = "Copyright {year} Samuel Smith."
enableInlineShortcodes = true
languageCode           = "en-AU"
title                  = "Playleft"
theme                  = "playleft"
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
ignoreLogs   = ['warning-goldmark-raw-html']
[pagination]
pagerSize = 6

[menu]

	[[menu.main]]
	identifier = "home"
	name       = "Home"
	url        = "/"
	weight     = 10

	[[menu.main]]
	identifier = "about"
	name       = "About"
	url        = "/about/"
	weight     = 20

	[[menu.main]]
	identifier = "posts"
	name 	   = "Posts"
	url	   = "/posts/"
	weight	   = 30

	[[menu.main]]
	identifier = "tags"
	name 	   = "Tags"
	url	   = "/tags/"
	weight	   = 40

	[[menu.main]]
	identifier = "contact"
	name 	   = "Contact"
	url	   = "/contact/"
	weight	   = 100

[taxonomies]
category = "categories"
series   = "series"
tag      = "tags"

[privacy]

	[privacy.vimeo]
	disabled = false
	simple   = true

	[privacy.x]
	disabled  = false
	enableDNT = true
	simple    = true

	[privacy.instagram]
	disabled = false
	simple   = true

	[privacy.youtube]
	disabled        = false
	privacyEnhanced = true

[services]

	[services.instagram]
	disableInlineCSS = true

	[services.x]
	disableInlineCSS = true

[markup]
	[markup.goldmark.renderer]
	unsafe = true
	[markup.goldmark.extensions.footnote]
	backlinkHTML = "<<"

[author]
  name = "Samuel Smith"
  email = "sam@playleft.com"

[Params]
mainSections = "post"
startdate    = "2025-05-12"
summary      = true
toc          = true

[markup.tableOfContents]
endLevel   = 6
ordered    = true
startLevel = 2
